routes:
    /sitemap/:
        template: sitemap
        content_type: text/xml
    /account/: members/account

collections:
    /:
        permalink: "/p/{slug}/"
        template: index

taxonomies:
    tag: /{slug}/
    author: /@{slug}/
