routes:
    /sitemap/:
        template: sitemap
        content_type: text/xml
    /account/: members/account

collections:
    /:
        permalink: "/{slug}/"
        template: index
        # Hide internal collection tags from homepage
        filter: tag:-[hash-wilayah,hash-tentang-pic,hash-resources,hash-ppn-ptll]

taxonomies:
    tag: "/{slug}/"
    author: "/{slug}/"
